In [1]:
import numpy as np
A=np.array([[1,2],[3,4],[5,6]])
#creation  d'une matrice (3,2)
print ('A=',A)#affichons la matrice

A= [[1 2]
 [3 4]
 [5 6]]


In [2]:
#afficher les dimensions de A
print('dimension de A', A.shape)

dimension de A (3, 2)


In [ ]:
#Transposée de A

In [3]:
B=A.T
print('B=',B)

B= [[1 3 5]
 [2 4 6]]


In [4]:
#creation d'une matrice B remplie de 1
C=np.ones((3,2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
#addition de A par C
D=A+C
D

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [6]:
print('dimensions de C:',C.shape)

dimensions de C: (3, 2)


In [7]:
#multiplication de A par B
E=A.dot(B)

In [8]:
E

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [9]:
print('E=',E)
print('E=',E.shape)

E= [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
E= (3, 3)
